version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart:
      on-failure
    ports:
      - 8081:80

  backend:
    container_name: backend
    build: ./backend
    networks:
      - db
    env_file:
      - .env
    restart:
      on-failure
    ports:
      - 4000:3000
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:12.12-alpine
    networks:
      - db
    env_file:
      - .env
    restart:
      on-failure
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata

volumes:
  pg-data:
    driver: local

networks:
  db: