export const USERNAME_LENGTH_MIN = 3;
export const USERNAME_LENGTH_MAX = 64;
export const PASSWORD_LENGTH_MIN = 3;
export const ABOUT_LENGTH_MIN = 2;
export const ABOUT_LENGTH_MAX = 200;
export const MONEY_NUMBER_PRECISION = 10;
export const MONEY_NUMBER_SCALE = 2;
export const WISH_NAME_LENGTH_MIN = 1;
export const WISH_NAME_LENGTH_MAX = 250;
export const WISH_DESCRIPTION_LENGTH_MIN = 1;
export const WISH_DESCRIPTION_LENGTH_MAX = 1024;
export const WISHLIST_NAME_LENGTH_MIN = 1;
export const WISHLIST_NAME_LENGTH_MAX = 250;
export const WISHLIST_DESCRIPTION_LENGTH_MIN = 1;
export const WISHLIST_DESCRIPTION_LENGTH_MAX = 1500;

export const HTTP_CODE_UNAUTHORIZED = 401;
export const HTTP_CODE_FORBIDDEN = 403;
export const HTTP_CODE_CONFLICT = 409;
export const HTTP_CODE_SERVER_ERROR = 500;

export const LENGTH_LIST_LAST_GIFTS = 40;
export const LENGTH_LIST_POPULAR_GIFTS = 20;
